### ISSUE TITLE
Local time ambiguity

### ISSUE THREAD

**Issue by gregjesl** [gregjesl/brutezone#6]
The following time zones fail the `timezone_gmt_time.c` unit test:
America/Glace_Bay
America/Goose_Bay
America/Halifax
America/Havana
America/Moncton
America/St_Johns
America/Thule
Atlantic/Bermuda

Discovered when merging #3

**Comment by gregjesl** [comment]
After manipulating the test more, it appears the issue is related to the ambiguity that @huelsenfruchtzwerg references in #3.

**Comment by gregjesl** [comment]
I'm inclined to write a function that determines if a local time is an "ambiguous" time--a time that could occur twice because of Daylight Savings Time.  Such a function could be used in the unit tests but may also be useful as a general function.

**Comment by huelsenfruchtzwerg** [comment]
That's not a bad idea. signature might be somethink like
`/*!
 * \brief determines if the given local time observes DST
 *
 * \param[in] timezone_name
 * \param[in] localtime
 *
 * \return 1 if the given timestamp observes dst, 0 if it doesn't,
 *         -1 if it is not defined due to daylight-time -> standard-time
 *         transition, -2 if the timezone was not found in the database or
 *         the given timestamp is outside of the database range.
 *
 * \note this function considers any time-period, that has a bigger offset
 *       than the one immediately before to be DST, even if the "historic"
 *       reason for this was something different.
 */
int timezone_is_dst(const char *timezone_name, time_t localtime);`

**Comment by huelsenfruchtzwerg** [comment]
https://nodatime.org/unstable/api/NodaTime.DateTimeZone.html#NodaTime_DateTimeZone_AtLeniently_NodaTime_LocalDateTime_
https://nodatime.org/unstable/api/NodaTime.DateTimeZone.html#NodaTime_DateTimeZone_AtStrictly_NodaTime_LocalDateTime_
Just checked how NodaTime handles these cases, as a reference for how it's handled elsewhere.
